### ISSUE TITLE
doubt about installation on mac or windows

### ISSUE THREAD

**Issue by Mc210** [fangohr/finmag#34]
Anyone know what are the instructions to install fing?

I think the manual it brings is not much use, i would like to install finmag on windows or os x operative system.

Regards,

**Comment by marijanbeg** [comment]
Hi @Mc210, thank you for your question. Unfortunately, the installation on Windows and MacOS is not easy at all. Therefore, we always recommend using finmag via Docker. Please refer to the README file where instructions how to use it can be found.

Please let us know if you have any further questions. I will close this issue now, but feel free to reopen it if necessary.
