### ISSUE TITLE
doubt about how i can create a geometry

### ISSUE THREAD

**Issue by Mc210** [fangohr/finmag#35]
Seeing the examples I have a doubt, Is it possible to build geometry from analytical functions?

for example using equation of a disk o ellipse?

Thanks

**Comment by marijanbeg** [comment]
Hi @Mc210, thank you for your question. The only way in finite elements to define a geometry is to create a mesh. For that you can have a look at Gmesh if the type of geometry you are looking for is not a part of FEniCS.

Please feel free to reopen this issue if you have any further questions on this topic.

**Comment by Mc210** [comment]
ok, but the problem is that this program builds geometry from geometric figures, I would like to build it from an analytical function such as the  region function of a cylinder, ellipsoid, etc. In oommf i use proc function. If I use geometric figures it will make it difficult for me to calculate the normal and tangential vectors to the surface.

Thanks

**Comment by marijanbeg** [comment]
Hi @Mc210, Finmag is a finite elements code and defining the geometry using analytic functions is not possible. However, you can use any available software to create a mesh and then use it in Finmag.
