### ISSUE TITLE
Basic question about installation and use

### ISSUE THREAD

**Issue by Mc210** [fangohr/finmag#37]
I have downloaded and installed Finmag via docker.

I have run the command "sudo docker run -ti -w =" / finmag "--rm finmag / finmag bash -c" py.test -v "". Show that everything is correct

It is assumed that all the necessary packages to run Finmag are installed in the environment or some language or program such as python, numpy etc must be installed? How can I run an example, for example std_prob_3?.

thanks

**Comment by marijanbeg** [comment]
Hi @Mc210,

Thank you for your question. Docker image contains everything you need to run a Finmag simulation. The recommended workflow, which I use myself is:

1. Write a simulation script, for instance `my_simulation.py` where Finmag simulation is defined.
2. Run the simulation inside Docker using:
   
    `docker run -ti -v $(pwd):/io --rm finmag/finmag bash -c "python my_simulation.py"`

3. After the simulation is complete. All files created by finmag will be in your working directory (at the place at which you ran the previous command).
4. From now on, all the data analysis can be done on host, where you can install anything you need. This step is completely independent from running Finmag simulation inside Docker.

An example workflow can be found in https://github.com/marijanbeg/2019-paper-bloch-point-stability repository, where I used a similar (but slightly more complicated) workflow.

I hope this answers your question. I am going to close this issue now, but of course, please feel free to reopen it for any further questions on this topic.
