### ISSUE TITLE
doubt about the format of the mesh file

### ISSUE THREAD

**Issue by Mc210** [fangohr/finmag#38]
I have a question about the type of mesh Finmag uses. In GMsh, I have built a tube, the file.geo is the following:

SetFactory ("OpenCASCADE");
Cylinder (1) = {0, 0, 0, 0, 40, 100, 2 * Pi};
Cylinder (2) = {0, 0, 0, 0, 40, 50, 2 * Pi};
BooleanDifference (8) = {Volume {1}; Delete; } {Volume {2}; Delete; };

This script must be loaded in Finmag or the mesh it generates (.msh) ?. Viewing the .geo files in the examples does not show numerical data, that's is the format?.

Thank you so much,

**Comment by marijanbeg** [comment]
Hi @Mc210,

Thank you for your question. Using gmsh you should:

1. Write `.geo` file where you describe the mesh. For instance, `my_mesh.geo`.

2. Run `gmsh` and generate mesh `.msh` file. For instance:

    `gmsh my_mesh.geo -3 -optimize -o my-mesh.msh`

3. Convert `.msh` to `.xml` which can be then read by dolfin (finmag):

    `dolfin-convert my_mesh.msh my_mesh.xml`

4. This gives you the `.xml` file which you can use to define a mesh in Finmag simulation:

   `mesh = df.Mesh('my_mesh.xml')`

There is an example of the convenience function which goes from `.geo` file to mesh object in https://github.com/marijanbeg/2019-paper-bloch-point-stability/blob/master/src/helpers.py#L7.

I will close this issue now, but if you have any further questions on this topic, please feel to reopen this issue.

Best,
Marijan

**Comment by Mc210** [comment]
Thanks that work!,  I  have other question of, ¿ how to save the different energies and the final vector of magnetization or vtk file in the same directory of the simulation file?.  I am having trouble creating new directories due to the permissions that I have

Thanks
