### ISSUE TITLE
Doubt about how save the results in the current directory

### ISSUE THREAD

**Issue by Mc210** [fangohr/finmag#39]
Thanks that work! (https://github.com/fangohr/finmag/issues/38#issuecomment-611486935), I have the last question , ¿ how to save the different energies and the final vector of magnetization or vtk file in the same directory of the simulation file?. I am not familiar with the syntax they occupy and I am having trouble creating new directories due to the permissions that I have

Thanks

**Comment by marijanbeg** [comment]
Hi @Mc210,

An example of saving magnetisation data in different directories can be found here: https://github.com/marijanbeg/2019-paper-bloch-point-stability/blob/master/src/stability.py

Different energies can be computed using, for example `sim.get_interaction('Exchange').compute_energy()`. All energy terms in the Hamiltonian can be accessed using `sim.get_intefaction_list()`.

Please feel free to reopen this issue if you have any further questions.
