### ISSUE TITLE
Doubt about how save the results in the current directory

### ISSUE THREAD

**Issue by Mc210** [fangohr/finmag#40]
Thanks, but the problem is that when I run the stability.py, I get the following error:

sudo docker run -ti -v $(pwd):/io --rm finmag/finmag bash -c "python stability.py"

[2020-04-09 14:48:22] INFO: Relaxation finished at time t = 8.2e-10.
Traceback (most recent call last):
  File "stability.py", line 48, in <module>
    os.makedirs(rdir)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '../results'

The same happens to me with some examples of Finmag. I don't know what happens

**Comment by marijanbeg** [comment]
What happens if you use `marijanbeg/bloch_point:finmag` docker image? More precisely, the command:

`sudo docker run -ti -v $(pwd):/io --rm marijanbeg/bloch_point:finmag bash -c "python stability.py"`

**Comment by marijanbeg** [comment]
Also, please pay attention to the fact that if you are in `dir1/dir2/` directory, call Finmag simulation and want to create a file in `dir1`, that is not possible. In that case, Fimag must be called from `/dir1`. Have a look at this Makefile: https://github.com/marijanbeg/2019-paper-bloch-point-stability/blob/master/Makefile

**Comment by Mc210** [comment]
I download the src folder, with the terminal in the src, I run the instruction:
sudo docker run -ti -v $ (pwd): / io --rm finmag / finmag bash -c "python stability.py"

with "sudo docker run -ti -v $(pwd):/io --rm marijanbeg/bloch_point:finmag bash -c "python stability.py"" I obtain the same error.

**Comment by Mc210** [comment]
When did you say that "Finmag must be called from dir1", that means the terminal must be in that directory?

**Comment by marijanbeg** [comment]
If you call Docker from `src` directory, then Docker has permissions only to that directory. So, you need to call Docker/Finmag from one level up to be able to create the directories on that path.

This is the line from the Makefile I referred to earlier (there is `cd src` before calling python):

`docker run -ti -v $$(pwd):/io marijanbeg/bloch_point:finmag bash -c "cd src; python stability.py"`

So, let's say you have `src` directory in `my_project`. You need to navigate to `my_project` (not `src`) and call Docker from there.

**Comment by Mc210** [comment]
Thanks so much!!, now is working.

**Comment by marijanbeg** [comment]
Great, I will close the issue now.
