### ISSUE TITLE
save the energy values

### ISSUE THREAD

**Issue by Mc210** [fangohr/finmag#41]
Hi ,

How can I save the values of the different energies, i.e, demag or exchange?, I have put sim.get_interaction ('Exchange'). compute_energy () after  sim.relax(stopping_dmdt=0.01) but nothing happens.  To relax the system, which method does Finmag occupy by default?

Thanks

**Comment by marijanbeg** [comment]
Hi @Mc210, this command gives you a number (`float`), which you can then save it any way you want.

**Comment by Mc210** [comment]
Thanks, have the same format that python 3.

Thats works

e_exc = sim.get_interaction('Exchange').compute_energy()
e_demag = sim.get_interaction('Demag').compute_energy()

with open("data_energies.txt", "a") as f:
    f.write("{} {}".format(e_exc, e_demag))
    f.close()

Is there any way to indicate the number of cores to the execution of the program?, I understand that the calculation of the magnetostatic field is parallelized

**Comment by marijanbeg** [comment]
Great. When using context manager (`with` statement) in Python, you do not need `f.close()` because it is done in the background.

Unfortunately, Finmag does not support running in parallel.

**Comment by Mc210** [comment]
Thanks, for save the final magnetization in the example, appear:

# Save the hdf5 file for data analysis.
h5_filename = '{}/{}'.format(rdir, basename)
sim.llg.m_field.save_hdf5(h5_filename, 0)
sim.llg.m_field.close_hdf5()

that's save the three components, mx my and mz?. Is possible to save in other format like irregular dat or csv?.

**Comment by marijanbeg** [comment]
Hi @Mc210, only saving magnetisation in HDF5 and VTK files is supported. However, if you want to save the magnetisation in CSV file format, it can be relatively easily done in Python.

**Comment by Mc210** [comment]
may be sim.schedule('save_m') is ok for that?

**Comment by marijanbeg** [comment]
Scheduler can be used, but `save_m` function should be written by yourself. Then, `save_m` function will be called during the simulation at regular intervals.

**Comment by Mc210** [comment]
i have used 

m_0_file = os.path.join(MODULE_DIR, "m_0.npy")
np.save(m_0_file, sim.m)

but the file m_0_file only have one column

**Comment by marijanbeg** [comment]
There are a few things you need to consider:

1. In finite elements, no order in the array of values exists like in finite differences. Therefore, you need to save both coordinates (`mesh.coordinates()`) and values (`sim.m.vector().array()`) to the file. Please refer to fenics 
2. It is very difficult to load the csv file back to Fenics, on which Finmag is based.

For details please refer to FeniCS documentation (https://fenicsproject.org).

**Comment by Mc210** [comment]
Thank you very much, I had not noticed that detail.

**Comment by Mc210** [comment]
I would like to test a vortex in a cylinder. I think the magnetization script would look something like this:

def vortex_init (rs):

     xs, ys, zs = rs
     phi = np.arctan2 (ys, xs)
     return np.array ([np.sin (phi), -np.cos (phi), 0])

but that instruction return a constant value, why?.

**Comment by marijanbeg** [comment]
Hi @Mc210, most probable reason why this happens is that the coordinates in the mesh are in meters, not nanometers. So instead of using `xs`, you should probably use `1e-9*XS`.
 
Or vice versa....

**Comment by Mc210** [comment]
Thank you very much for the help provided

**Comment by Mc210** [comment]
Hi,

I have problem with the magnetization, when open the file with Matlab or python I  can  only see 1 column.

Also, I have tried to save the coordinates and the vector on txt format:

pos = mesh.coordinates ()
vect = sim.m

"Sim.m.vector (). Array ()" does not work

with open ("xpos.txt", "a") as f:
     f.write ("{}". format (pos))
     f.close ()

with open ("mag.txt", "a") as f:
     f.write ("{}". format (vect))
     f.close ()

the file xpos.txt is correct, but  the file mag.txt have only one column, is that correct?

Thanks

**Comment by marijanbeg** [comment]
Hi @Mc210, `sim.m` is just a dolfin function. Can you please try:

`vect = sim.llg.m_field.f.vector().array()`

**Comment by Mc210** [comment]
Thanks, but I obtain the same column vector, is stranger. I would expect it to be a 3 column vector

**Comment by marijanbeg** [comment]
Hi @Mc210, field representation in finite elements is much more complicated than in the case of finite differences and unfortunately it is not trivial to simplify that. The array you get is usually in the `xyzxyzxyz...` or `xxx...yyy...zzz...` order. That is why HDF5 is a recommended way of saving data.

However, if you really need the components of m, the least painful way of getting the data is:

```
mx, my, mz = [], [], []  # Empty lists where magnetisation components will be saved
for coord in self.mesh.coordinates():
    m_at_point = sim.llg.m_field.f(coord)  # This samples the field at coord and gives (mx, my, mz) at that point
    mx.append(m_at_point[0])  # Extract x-component and append it to the list
    my.append(m_at_point[1])
    mz.append(m_at_point[2])
```

**Comment by Mc210** [comment]
Thanks so much, thats work perfecttly.  I think I have to read the documentation to understand why the magnetization vector in the H5 format has only one column and the coordinate vector 3.

**Comment by marijanbeg** [comment]
Great, you are welcome.

I am going to close this issue now. Please feel free to reopen.
