### ISSUE TITLE
Condition of meshs for Finmag

### ISSUE THREAD

**Issue by tnyal** [fangohr/finmag#42]
Hi, 

What conditions must the mesh have to be used  on Finmag?,

Can it be used to study curved geometries ?, such as spheres, cones, etc.

**Comment by marijanbeg** [comment]
Hi @tnyal, thank you very much for your question. In general, any finite elements mesh (including spheres, cones, etc.) can be used in Finmag. You can use an external package to define your mesh (for instance Gmsh).

Please let us know if you have any further questions.

I will close this issue now, but please feel free to reopen it if I did not answer your question.
