### ISSUE TITLE
Error with cubic anisotropy

### ISSUE THREAD

**Issue by Mc210** [fangohr/finmag#43]
I have an error when I try to simulate two or more bodies with cubic anisotropy, in this case, a cuboid. Following the example  Histeresys.py

import numpy as np
import dolfin as df
from finmag import Simulation
from finmag.energies import Exchange, Demag, CubicAnisotropy
from finmag.util.consts import mu0

Ms = 876626  # A/m
A = 1.46e-11  # J/m

K1 = -8608726
K2 = -13744132
K3 =  1100269
u1 = (1, 0,0)
u2 = (0,  1,0)
u3 = (0, 0,1)  # perpendicular to u1 and u2

mesh = df.Mesh('test.xml')
sim = Sim(mesh, Ms, unit_length=1e-9)
m_init = m_init = (1, 0, 0)

sim.add(Exchange(A))
sim.add(Demag())
sim.add(CubicAnisotropy(K1, u1, K2, u2, K3, u3))

# Turn off precession to speed up simulations.
sim.do_precession = False

# Initialise the system.
sim.set_m(m_init)

sim.relax(stopping_dmdt=0.01)

I have the following error when considering an isolated cuboid:

Traceback (most recent call last):
  File "Sim_uniform.py", line 53, in <module>
    sim.add(CubicAnisotropy(K1, u1, K2, u2, K3, u3))
  File "/finmag/src/finmag/energies/cubic_anisotropy.py", line 43, in __init__
    self.u3_value = np.cross(u1, u2)  # u3 perpendicular to u1 and u2
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 1673, in cross
    raise ValueError(axis_msg.format('a'))
ValueError: 'axisa' out of bounds
bash: line 1:     6 Aborted                 python Sim_uniform.py

**Comment by marijanbeg** [comment]
Hi @Mc210, it seems the error arises because of the way you define cubic anisotropy. The class "constructor" signature is `def __init__(self, u1, u2, K1, K2=0, K3=0, name='CubicAnisotropy', assemble=False)`. Please pay attention to the order and number of arguments.
