### ISSUE TITLE
requirement of the mesh for Finmag

### ISSUE THREAD

**Issue by tnyal** [fangohr/finmag#44]
Hi,

I have a question about requirement of the mesh. I need to make a hysteresis loop of a two interacting sphere of cobalt for contrast my results on mumax3. I have built the geometry on gmsh.

The radii of the spheres are 10 nm. 
When I make the hysteresis curve considering a mesh with a characteristic maximum and minimum length and of 2 nm, 1 nm and 0.5 I get very different results. Thats is normal?

**Comment by marijanbeg** [comment]
Hi @tnyal,

There is an example of two coupled disks in finmag (https://github.com/fangohr/finmag/blob/master/doc/ipython_notebooks_src/tutorial-coupled-relaxation-of-two-nanodisks.ipynb). You can refer to it and see if there are any similarities with your problem.
