### ISSUE TITLE
about cubic anisotropy

### ISSUE THREAD

**Issue by Mc210** [fangohr/finmag#45]
I have placed the terms following with the respective class, but it also gives an error, following the cubic_anisotropy_test.py . If I put:

K1 = -100e3
K2 = -100e3
K3 = -100e3
u1 = (0,0,1)
u2 = (0,1,0)

sim.add(CubicAnisotropy(u1, u2, K1, K2, K3))

the error is

  ydot[:] = self.solve_for(y, t)
  File "/finmag/src/finmag/physics/llg.py", line 237, in solve_for
    value = self.solve(t)
  File "/finmag/src/finmag/physics/llg.py", line 242, in solve
    self.effective_field.update(t)
  File "/finmag/src/finmag/physics/effective_field.py", line 92, in update
    self.H_eff += interaction.compute_field()
  File "/finmag/src/finmag/energies/cubic_anisotropy.py", line 113, in __compute_field_directly
    m, self.Ms, self.H, self.uv, self.K1, self.K2, self.K3)
ValueError: compute_cubic_field: Ms: Expected array of shape (872), got (3494)
bash: line 1:     6 Aborted

Thanks you

**Comment by marijanbeg** [comment]
Hi @Mc210, it is a bit unclear what went wrong in the error message you sent us. Can you please send me the whole script you use (or even better a minimal failing example)? Is the magnetisation set right?

Best,
Marijan

**Comment by Mc210** [comment]
Thanks, for example a cuboid.

The gmsh file is:

SetFactory("OpenCASCADE");
Box(1) = {0, 0, 0, 40, 40, 40};

Physical Volume(1) = {1};

Mesh.CharacteristicLengthMax = 2;
Mesh.CharacteristicLengthMin = 2;

With dolfin I build the cuboid.xml file.

The simulation file is:

`#!/usr/bin/python
import os
import gc
import sys
import pickle
import time
import logging
import dolfin as df
import numpy as np
from scipy.optimize import bisect
from finmag import Simulation as Sim
from finmag.energies import Exchange, CubicAnisotropy
from finmag.util.consts import mu0

MODULE_DIR = os.path.dirname(os.path.abspath(__file__))
m_0_file = os.path.join(MODULE_DIR, "m_0.npy")
m_at_crossing_file = os.path.join(MODULE_DIR, "m_at_crossing.npy")

basename = 'Test_Finmag'
rdir = '../Sim_cuboid/{}'.format(basename)
if rdir != './' and not os.path.exists(rdir):
    os.makedirs(rdir)

Ms = 860e3  
A = 1.3e-11  

mesh = df.Mesh('Cuboid.xml')

K1 = -10e3
K2 = -10e3
K3 = -10e3
u1 = (0, 1, 0)
u2 = (0,  0, 1)

sim = Sim(mesh, Ms, unit_length=1e-9)

sim.add(Exchange(A))
sim.add(CubicAnisotropy(u1, u2, K1, K2, K3))

sim.do_precession = False

m_init = (1, 0, 0)
sim.set_m(m_init)

sim.relax(stopping_dmdt=0.01)

pvd_filename = '{}/{}.pvd'.format(rdir, basename)
sim.save_vtk(pvd_filename, overwrite=True)`

Thanks

**Comment by marijanbeg** [comment]
Thank you for the example. This is very strange. I cannot see anything wrong with the code and the tests cover this behaviour very well. I can suggest writing `sim.add(CubicAnisotropy(u1=u1, u2=u2, K1=k1, K2=K2, K3=K3))` just to make sure the class is properly instantiated. If that does not work, you can have a look at this example: https://github.com/fangohr/finmag/blob/076358b49bd8ffbfc93b50e527ea70e46e9c4440/src/finmag/tests/test_anis.py and try to rewrite it.

Also, why do you use negative values of K?

**Comment by Nicobz22** [comment]
Thanksm I think it worked with the original file, with respect to the sign, I just wanted to see if I accepted the minus sign as a difficult axis.

Do you know if it is possible in Finmag to load the mesh through a vtk file?

**Comment by marijanbeg** [comment]
Hi @Nicobz22, thank you for letting me know. Regarding your question, loading a mesh from a VTK file is not possible.

I will close this issue now, but please reopen it if you have any further questions on this topic.
